slack:
  name:             BigQuery Table Autocreator
  channel:          your-channel
  webhook:          "https://hooks.slack.com/services/x/y/z"

projects:
  - project_id:     your-gcp-project
    bigquery:
      dataset:      your_bq_dataset
      prefix:       events
      schema_path:  ./configs/sample_schema.json
